apiVersion: v1
kind: Service
metadata:
  name: nginx-ha-service
  namespace: web-apps
spec:
  selector:
    app: nginx-ha
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
